### ISSUE TITLE
Use out-of-tree build

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#1]
Awesome!

You can simplify building by using out-of-tree builds. This lets you share a checkout. You can also get the current host triple from ``config.guess``.

```
git clone https://github.com/python/cpython.git

cd cpython
mkdir -p builddir/host
mkdir -p builddir/wasi

# if you use an existing checkout, you must run "make clean"

pushd builddir/host
../../configure -C
make -j$(nproc)
popd

pushd builddir/wasi
emconfigure ../../configure -C ... --build=$(../../config.guess)
popd
```

**Comment by emmatyping** [comment]
Cool! I'll tweak the scripts to use this, that's very handy.

I take it you are currently working on WASI then :)

How are you planning on dealing with pthread?

**Comment by tiran** [comment]
> How are you planning on dealing with pthread?

I dont' know ... Hope that the problem magically goes away? 

Disclaimer: I have zero experience with WASM / WASI / Emscripten stack. I'm more of a C / Security / build infra person. I know how to hack m4, autoconf and make.

**Comment by emmatyping** [comment]
> I dont' know ... Hope that the problem magically goes away?

Unfortunately I won't expect that to happen upstream for a long time. WASM threads aren't really amendable to be a basis for pthreads, as far as I understand them. You can shim the headers in like in https://github.com/kildom/clang-wasi-port but that will fail at runtime.

Unfortunately I think threadless CPython builds will be the only feasible solution (but I know those were ripped out a long time ago).

> I have zero experience with WASM / WASI / Emscripten stack

I also only have a bit of experience from WASM/Rust and some past attempts to get Python on WASM ports working, but I'm not super familiar with Python's build system (at least, I wasn't before learning about a lot recently :)

**Comment by emmatyping** [comment]
Fixed in https://github.com/ethanhs/python-wasm/commit/29a5e7e91d0b41b2b1139403dc87ad38951e2142, thanks for pointing me to it!
