### ISSUE TITLE
bzip2 breaks build

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#16]
emscripten's bzip2 port breaks the build for me. I'm not entirely sure what is going on. It looks like the build archive includes the main function from ``mk251.c``.

```
wasm-ld: error: duplicate symbol: main
>>> defined in Programs/python.o
>>> defined in /usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten/libbz2.a(mk251.c.o)
```

I suggest to disable bzip2 for now and investigate later.

**Comment by tiran** [comment]
Upstream PR with fix: https://github.com/emscripten-core/emscripten/pull/15751

**Comment by emmatyping** [comment]
I think this has been solved by moving to Emscripten 3.1.1?

**Comment by emmatyping** [comment]
Oh we should actually add it to the build scripts :)

**Comment by brettcannon** [comment]
Can this be closed?

**Comment by emmatyping** [comment]
No, I think bzip2 is still not enabled in the build (not sure if the fix is available in upstream emscripten, I'll take a look a bit later)

**Comment by tiran** [comment]
Emscripten port libbz2 is fixed. We need to adjust config.site override and the build scripts

**Comment by brettcannon** [comment]
Looking at https://github.com/python/cpython/blob/main/Tools/wasm/config.site-wasm32-emscripten and https://github.com/python/cpython/blob/main/Tools/wasm/config.site-wasm32-wasi , I don't see any bzip2-specific overrides. So based on https://github.com/python/cpython/blob/main/Tools/wasm/README.md, the only real change necessary is to add `bzip2` to the `embuilder` lines in the build scripts.
