### ISSUE TITLE
Remove need for `READELF=true`

### ISSUE THREAD

**Issue by brettcannon** [ethanhs/python-wasm#19]
When I looked at this a little while back I believe there was only one use of `READELF` in the code base and it was in `setup.py` for curses. Can probably make the existence of `READELF` be optional.

**Comment by tiran** [comment]
``readelf`` is required for cross-compiling to detect if readline or editline need extra linking with curses or tinfo. We should be able to get rid of the special case after Erlend and I have ported the last remaining modules to pkg-config.

**Comment by brettcannon** [comment]
@tiran do you happen to have an issue tracking that work that we can paste here as a reference?

**Comment by tiran** [comment]
Erlend and I are using https://bugs.python.org/issue45847 to track configure.ac improvements. curses and readline are two of very few packages that have not been ported yet.

**Comment by emmatyping** [comment]
I think this can be closed? We don't need READELF anymore in the build scripts.

**Comment by tiran** [comment]
Correct, the config.site overrides take care of readelf.
