### ISSUE TITLE
sysconfig info module is misnamed/not found

### ISSUE THREAD

**Issue by emmatyping** [ethanhs/python-wasm#2]
It seems that a `_sysconfigdata__linux_x86_64-linux-gnu.py` is generated under `lib.wasm32-unknown-emscripten-3.11`, which seems wrong?

Either way it isn't being included when running altinstall, so `sysconfig.get_config_vars()` doesn't work.

**Comment by tiran** [comment]
I have seen the issue before when cross compiling for other targets. It looks like a bug in sysconfig. I have created the upstream bug https://bugs.python.org/issue45909

**Comment by emmatyping** [comment]
I think this and the linked BPO were fixed by https://github.com/python/cpython/pull/29835 ?

**Comment by tiran** [comment]
Yes, ``sysconfig.get_config_vars()`` now works for me with CI build.
