### ISSUE TITLE
Make `--enable-big-digits=30` the default

### ISSUE THREAD

**Issue by brettcannon** [ethanhs/python-wasm#20]
Any reason to not make this be automatic when `wasm32` is set?

**Comment by emmatyping** [comment]
Yeah this would be a good thing to upstream to CPython.

**Comment by emmatyping** [comment]
We should also probably make `--without-pymalloc` and `--with-ensurepip=no` the default on WASM, I don't see either of those ever getting used.

**Comment by brettcannon** [comment]
Created #22 and #23 for `--without-pymalloc` and `--with-ensurepip`, respectively.

**Comment by tiran** [comment]
Before we hard-code ``--enable-big-digits=30`` and ``--without-pymalloc`` in configure and include, I would first like to understand and document the reason for the settings.

``--without-ensurepip`` is obvious for emscripten, though.

**Comment by brettcannon** [comment]
The explanation for that setting is given at https://github.com/pyodide/pyodide/blob/771693ff99c55f5292823d86a95702291cf08755/cpython/Makefile#L129-L135

**Comment by tiran** [comment]
Thanks, I missed the comment there. 

Fixed in https://github.com/python/cpython/pull/29887
