### ISSUE TITLE
Make `--disable-ipv6` the default?

### ISSUE THREAD

**Issue by brettcannon** [ethanhs/python-wasm#21]
Or is the hope that Emscripten may support it someday, and so making it an opt-out still makes sense?

**Comment by emmatyping** [comment]
We should probably look into where things break and ask if upstream has plans to support it (they may already, I'm not certain). If we can enable it, it would be good to do so.

**Comment by tiran** [comment]
I wonder why the flag is necessary. Is this perhaps related to ``buggy_getaddrinfo`` check in configure? The check uses ``AC_RUN_IFELSE``, which obviously does not work for cross compiling. The ``ac_cv_buggy_getaddrinfo=no` override` in ``CONFIG.SITE`` should be good enough to work around the problem.
