### ISSUE TITLE
Modify heap size or allow heap growth

### ISSUE THREAD

**Issue by emmatyping** [ethanhs/python-wasm#29]
When running
```
help('modules')
```

it causes Python to OOM (the heap is limited to 16MB). We should consider using either
1.  `-s INITIAL_MEMORY=X` for something like 20-30MB or
2.  just allow memory growth via `-s ALLOW_MEMORY_GROWTH=1`.

We should maybe also compile with `-s ABORTING_MALLOC=0` which makes `malloc()` return NULL, which will give people a more familiar Python traceback rather than the following:

```
Uncaught RuntimeError: Aborted(Cannot enlarge memory arrays to size 16855040 bytes (OOM). Either (1) compile with  -s INITIAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 )
```

**Comment by brettcannon** [comment]
Are their novel drawbacks for going with the memory growth option compared to the usual potential of things getting out of hand (which I would still assume the browser would take care of)? Otherwise the `ABORTING_MALLOC=0` option definitely sounds like a a minimum change to go with.

**Comment by tiran** [comment]
Does ``ALLOW_MEMORY_GROWTH=1`` have performance implications? I vaguely remember that some document mentioned that growing memory required regular checks or a callback to be efficient.

**Comment by emmatyping** [comment]
`ALLOW_MEMORY_GROWTH` was enabled in https://github.com/python/cpython/pull/30552, it seems almost required. There is a performance  hit when used, but I think since most things will require a lot more than 16MB memory we should enable it anyway.

**Comment by brettcannon** [comment]
Should we close this?

**Comment by emmatyping** [comment]
Yeah, allowing memory growth seems to be the most reasonable solution to this.
