### ISSUE TITLE
Borrow web REPL from Pyodide?

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#32]
The UX of our WASM builds are suboptimal. The modal window input and output to webdev console are not user friendly. Pyodide has a well working REPL, https://pyodide.org/en/stable/console.html . How much would it take to "borrow" the repl from the project?

Also see: https://github.com/pyodide/pyodide/issues/2000

**Comment by emmatyping** [comment]
Pyodide runs things in a webworker https://pyodide.org/en/stable/usage/webworker.html#using-from-webworker if I'm not mistaken, and they have some support infrastructure to loading/interacting with Emscripten's console streams e.g. https://github.com/pyodide/pyodide/blob/20d760ea7c8de6c8f9ef8a4ca431c5eed1f125da/src/js/module.js#L43

**Comment by brettcannon** [comment]
I think once we have the build where we want it we should definitely talk to the Pyodide folks about contributing something (but we may need/want to figure out where we want this work to live permanently before we do that so everyone gets the same experience/benefit, e.g. should we move this repo to the psf or python org, create a new one, or leave it here?).

**Comment by alexmojaki** [comment]
The standard Pyodide console still uses modal window input, which is especially a problem for pdb. If you want input in the REPL, I got it working in https://futurecoder.io/, that's the only currently working example that I know of. There's some more info here: https://github.com/pyodide/pyodide/issues/550#issuecomment-903182645

**Comment by emmatyping** [comment]
I think a solution like what is done with futurecoder is promising. We will probably want to make changes to CPython like in Pyodide which allows customization via callbacks for stdin/out/err since many environments will want to customize that.

**Comment by pmp-p** [comment]
why not a very small line editing emulation and a event based loop repl which could allow for features of the 3.8+ asyncio console ? a bit like https://pmp-p.github.io/wasi/wapy.html (a minimal python vm)  or https://pmp-p.github.io/python3.html ( asyncio + cpython 3.8 )
it would be nice to have something closer to what the javascript console offers.
 
edit/ i don't think https://github.com/ethanhs/python-wasm/pull/47 allows direct access to browser graphic thread or webgl when needed ( eg  pygame, panda3d, pysdl2 ... )

**Comment by brettcannon** [comment]
Is this worth keeping open in the face of what we have with repl.ethanhs.me?

**Comment by emmatyping** [comment]
I think that the repl Katie wrote works well to solve this issue :)
