### ISSUE TITLE
Set up build container for VS Code / GitHub Codespaces

### ISSUE THREAD

**Issue by brettcannon** [ethanhs/python-wasm#33]
Just need to include https://code.visualstudio.com/docs/remote/devcontainerjson-reference. That way you can dev using Codespaces with zero setup or open the repo in VS Code and it will ask if you want to reopen the workspace in the container.

**Comment by emmatyping** [comment]
Related https://github.com/ethanhs/python-wasm/issues/8

I think we can just use Christian's container image for this? I haven't actually used dev containers yet, but I've been meaning to try them.

**Comment by brettcannon** [comment]
Yep, we _should_ be able to specify Christian's container.

**Comment by tiran** [comment]
My container is a standard container image for x86_64. The build process is now mostly automated, too. I may hook up a cron job in the future, too.
