### ISSUE TITLE
Emscripten build with NODERAWFS=1

### ISSUE THREAD

**Issue by thomasballinger** [ethanhs/python-wasm#36]
It might be helpful for tests? being in a more familiar environment? to do an emscripten build that uses the native filesystem, which is possible with [NODERAWFS](https://github.com/emscripten-core/emscripten/blob/fde55d2f0f54f167a64a77ed013d2bbf22ab152d/src/settings.js#L881-L892) replacing the Emscripten in-memory filesystem. This would get us close to something like `node python.js script.py`.

~~FIle permissions don't quite work the same~~ There are some limitations to going through this layer, but it's pretty seamless for the filesystem access that node does provide. This might let folks install the emscripten-compiled version of Python alongside other python builds like pypy.

[WASI support](https://github.com/ethanhs/python-wasm/issues/18) seems strategically more important, but this could be a useful foothold.

**Comment by emmatyping** [comment]
Yeah more broadly we should try building with Emscripten targeting node as that will be easier to test

**Comment by emmatyping** [comment]
Fixed in https://github.com/python/cpython/pull/30552
