### ISSUE TITLE
configure checks for case-insensitive build directory sets BUILDEXEEXT=.exe

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#44]
A user on Discord informed me that they are getting ``python.exe`` instead of ``python.wasm`` on macOS.

**Comment by thomasballinger** [comment]
If I understand this right, I have a branch where I fixed some of these before moving over to linux, I can look into this

**Comment by tiran** [comment]
https://github.com/python/cpython/blob/1a4d1c1c9b08e75e88aeac90901920938f649832/configure.ac#L1110-L1118

**Comment by brettcannon** [comment]
Is there a reason not to use `EXEEXT` when defined for `BUILDEXEEXT`?

**Comment by brettcannon** [comment]
@thomasballinger did you ever find the branch with the fix for this?

**Comment by brettcannon** [comment]
I _think_ the solution is to change https://github.com/python/cpython/blob/1a4d1c1c9b08e75e88aeac90901920938f649832/configure.ac#L1110 to be `if test -d casesensitivetestdir && text -z $ac_exeext`. When I am on my Mac I will give it a try.

**Comment by brettcannon** [comment]
Have a fix in https://github.com/python/cpython/pull/31593 .

**Comment by thomasballinger** [comment]
Sorry about that, next got to this.

**Comment by brettcannon** [comment]
@thomasballinger if you can review my PR at https://github.com/python/cpython/pull/31593 that would be appreciated!

**Comment by thomasballinger** [comment]
@brettcannon this looks good to me, this was one of the things I remember fixing on that branch. Another was https://github.com/ethanhs/python-wasm/pull/54. I'm not a cpython reviewer so can't review but commented that it makes sense.
