### ISSUE TITLE
https://repl.ethanhs.me/worker/python.wasm is served with wrong content type

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#50]
Firefox refuses to start the demo repl because the wasm file is served with wrong content type:

```
wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'application/octet-stream' expected 'application/wasm'
```

**Comment by emmatyping** [comment]
Huh, it seems nginx didn't have the wasm application type available. I believe it should be fixed now. Let me know if not and I will override that path explicitly!

**Comment by tiran** [comment]
REPL now works in Firefox. Thanks!

**Comment by emmatyping** [comment]
Great! FWIW I think it was working for me on nightly, so maybe this behaviour was changed.

I also added credits and a link back to this repo :)
