### ISSUE TITLE
fetch-python.sh:  no /bin/env 

### ISSUE THREAD

**Issue by yarko** [ethanhs/python-wasm#52]
Ubuntu 20.04 - there is no /bin/env --- it's /usr/bin/env

This applies to all *.sh files in this repo.

**Comment by emmatyping** [comment]
I am running stock Ubuntu 20.04 desktop and server on several machines and they all seem to have /bin/env. Are you running a derivative?

**Comment by emmatyping** [comment]
It seems though that /usr/bin/env is the POSIX spec, so we should probably switch to that anyway, thanks for the report!

**Comment by yarko** [comment]
my desktop is an long-time-ago install (updated regularly);  my laptop I reinstalled recently - it has (indeed) both /bin/env and /usr/bin/env ...

**Comment by emmatyping** [comment]
Strange! Well thanks for reporting :)
