### ISSUE TITLE
best practice to detect emscriptened platform ?

### ISSUE THREAD

**Issue by pmp-p** [ethanhs/python-wasm#72]
edited to keep only what could be best or that can match C 
'emscripten' should be mentionned here https://docs.python.org/fr/3.11/library/sys.html#sys.platform
________
**Recommended one liners for now:**

The matching C tags  would be  ```__wasi__``` and ```__EMSCRIPTEN__```
```
if __import__('os').uname().machine.startswith("wasm"):
    print("detected webassembly")
   __wasi__ = True

if __import__('sys').platform == "emscripten":`
    print("detected emscripten")
    __EMSCRIPTEN__ = True
```

ref: wasi https://reviews.llvm.org/rGc1eee1d659155b99fac63cbf72491c27106f0481

**Comment by tiran** [comment]
You can also use the machine information field from ``os.uname()`` or the ``platform`` module. I recommend that you use ``startswith("wasm")`` to support wasm32 and wasm64.

```
>>> import sys
>>> sys.platform
'emscripten'

>>> import os
>>> os.uname()
posix.uname_result(sysname='Emscripten', nodename='emscripten', release='1.0', version='#1', machine='wasm32')
>>> os.uname().machine.startswith("wasm")
True

>>> import platform
>>> platform.machine()
'wasm32'
```
