### ISSUE TITLE
Build container with all dependencies

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#8]
I have created and pushed a build container image with all build dependencies pre-installed and emcc ports pre-seeded. The container might be useful for others that like to play around with emscripten and Python WASM. The image is pretty big and experimental. It works for me must of the time, though.

```
$ cd cpython
$ podman run --rm -ti -v $(pwd):/python-wasm/cpython:Z quay.io/tiran/cpythonbuild:ubuntu-impish-wasm
# . /activate
# ./build-python-build.sh
...
```

On Docker-based systems, do
```
docker run --rm -ti -v $(pwd):/python-wasm/cpython quay.io/tiran/cpythonbuild:ubuntu-impish-wasm
```

**Comment by emmatyping** [comment]
That's great! If you want to add the Dockerfile to this repo you should make a PR, I was thinking about doing this as well :)

**Comment by tiran** [comment]
I'm maintainer a set of images and Dockerfiles for testing CPython on various distros and archs. The Dockerfile for wasm builds is https://github.com/tiran/cpython_builddep/blob/main/wasm/Dockerfile.ubuntu-impish-wasm .

**Comment by emmatyping** [comment]
Oh great! Well in that case we should probably update the README to point to that :)

BTW, I added you and Brett to the repo.

**Comment by brettcannon** [comment]
Can this be closed, or is the container by @tiran missing something?

**Comment by emmatyping** [comment]
I think this can be closed.
