### ISSUE TITLE
Non pure python libs

### ISSUE THREAD

**Issue by svax974** [ethanhs/python-wasm#88]
Hello, this is just a question.
I'm only starting to look at wasm stuff and have a bunch of python scripts I could try to run on browsers and I'm particularly interested in that.
But I wish to know if there is a way to have python-wasm working with non pure python libs, I'm particularly thinking about ta-lib (the python port that still relies on libta/C) ?
As far as I understood, pyodide can't do that at least for now.

Thanks !

**Comment by pmp-p** [comment]
Hi, to compile modules for stock python-wasm you could get inspiration from https://github.com/pygame-web/python-wasm-sdk. If you want to use dynamic modules loading though you need to rebuild with ctypes enabled which is not the default iirc.
Here some modules that were successfully compiled https://github.com/pygame-web/archives/tree/main/repo/pkg and you can import them from the console ( eg with pypa/installer which is provided in the demo https://pygame-web.github.io/showroom/pythongit.html ).
 For pyodide you need to look at pyodide-build tool but produced modules won't load in stock cpython for various wasm compatibility reasons ( see wasm MVP and experimental extensions ).

**Comment by svax974** [comment]
Thank you for the answer.
Unfortunately, I'm not that advanced in all that Python/WASM stuff yet, just discovering.
And to be honest, I don't understand every concepts yet and I'm still a bit lost.

I'm looking to use TALib (which is not pure python), numpy and ccxt in a python program that I'd like to run in a browser.
I got a few basic things to work with dyodide but apparently it can't load a non pure python module so this is a no go for now.

Would that be possible to compile TALib with python-wasm-sdk and make it useable in a browser ?
How did you get all those in the pkg repo ? "Simply" building them with python3-wasm instead of python3 ?
Sorry for the noob questions :)

**Comment by pmp-p** [comment]
> Would that be possible to compile TALib with python-wasm-sdk and make it useable in a browser ?

Ymmv, you'll have to try : sometimes is just as easy as calling `/opt/python-wasm-sdk/python3-wasm setup.py bdist_wheel` sometimes it's just too much work to adapt. You can also try to post relevant information here and wait for someone passing by to solve it https://github.com/pygame-web/pkg-porting-wasm/issues

**Comment by svax974** [comment]
I'm trying and immediately have a problem I don't understand. Switching to pkg-porting-wasm issues.
Thanks.
