### ISSUE TITLE
python-wasm.org

### ISSUE THREAD

**Issue by williamstein** [ethanhs/python-wasm#89]
Hi,

I don't know if there is any interest in python-wasm.org, but it was a domain I was renting until yesterday.  I'm not using the name anymore, so I let it expire.  I'm just letting the devs of this project know, in case anybody wants to rent it.  There's no coordination with me necessary, since I didn't renew it.   

Anyway, once one of you sees this, please close this issue.  Sorry for any noise.

 -- William (wstein @ gmail.com)

**Comment by emmatyping** [comment]
Thank you for sharing! I don't think I personally will be using that domain but perhaps someone else will find it useful.
