### ISSUE TITLE
Shell scripts are missing error handling

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#9]
Shell scripts continue when something goes wrong. What do you think about adding ``set -e`` to all scripts?

**Comment by emmatyping** [comment]
Yes, we should definitely do this eventually. However, some things "fail" even though they work correctly, so we may need to play some back and forth with the build process to get things to complete fully.

**Comment by brettcannon** [comment]
What things fail that worked appropriately for building? Just looking for a task list to help drive down so we can get CI up.

**Comment by emmatyping** [comment]
I think I was seeing the output of certain extensions failing to be built, but I think `_ctypes` is the last one to fail to build?

**Comment by brettcannon** [comment]
Does `_ctypes` even make sense to provide?

**Comment by rth** [comment]
> Does _ctypes even make sense to provide?

@hoodmane managed to make it work with https://github.com/hoodmane/libffi-emscripten but indeed maybe for an initial build to iterate fast it might not be critical.

**Comment by tiran** [comment]
``_ctypes`` build is failing with a noise error message because it's not ported to new configure-based detection system yet. Same with readline and uuid.

**Comment by pmp-p** [comment]
maybe related https://bugs.python.org/issue14527 + https://github.com/python/cpython/pull/20451
btw original ffi-wasm bits come from there https://github.com/brion/libffi/tree/emscripten-work/src/wasm32

**Comment by brettcannon** [comment]
Checking through [a recent cron-based CI run](https://github.com/ethanhs/python-wasm/actions/runs/1827332657), these are the only failures I saw:
1. https://github.com/ethanhs/python-wasm/runs/5150975628?check_suite_focus=true#step:7:597
2. https://github.com/ethanhs/python-wasm/runs/5151002241?check_suite_focus=true#step:8:245

Should we add `set -e` to everything but those two situations?
